/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const BookingType = IDL.Variant({
  'local' : IDL.Null,
  'roundTrip' : IDL.Null,
  'oneWay' : IDL.Null,
});
export const BookingInput = IDL.Record({
  'submitterName' : IDL.Text,
  'submitterMobile' : IDL.Text,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'commission' : IDL.Nat,
  'submitterWhatsApp' : IDL.Text,
  'pickupCity' : IDL.Text,
  'pickupState' : IDL.Text,
  'driverEarning' : IDL.Nat,
  'bookingType' : BookingType,
  'dropState' : IDL.Text,
  'dropCity' : IDL.Text,
});
export const BookingId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FacilityInput = IDL.Record({
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const FacilityId = IDL.Nat;
export const CabId = IDL.Nat;
export const Cab = IDL.Record({
  'id' : CabId,
  'carModel' : IDL.Text,
  'driverMobile' : IDL.Text,
  'createdAt' : IDL.Int,
  'vendorId' : IDL.Principal,
  'rcBook' : IDL.Text,
  'driverName' : IDL.Text,
});
export const BookingStatus = IDL.Variant({
  'new' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DriverDetails = IDL.Record({
  'carModel' : IDL.Text,
  'mobile' : IDL.Text,
  'rcBook' : ExternalBlob,
  'driverName' : IDL.Text,
});
export const Booking = IDL.Record({
  'id' : BookingId,
  'status' : BookingStatus,
  'submitterName' : IDL.Text,
  'driverDetails' : IDL.Opt(DriverDetails),
  'submitterMobile' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'time' : IDL.Text,
  'vendorPrincipal' : IDL.Principal,
  'commission' : IDL.Nat,
  'submitterWhatsApp' : IDL.Text,
  'pickupCity' : IDL.Text,
  'pickupState' : IDL.Text,
  'driverEarning' : IDL.Nat,
  'bookingType' : BookingType,
  'dropState' : IDL.Text,
  'vendorName' : IDL.Text,
  'dropCity' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'newBookings' : IDL.Nat,
  'cancelledBookings' : IDL.Nat,
  'totalBookings' : IDL.Nat,
  'approvedVendors' : IDL.Nat,
  'confirmedBookings' : IDL.Nat,
  'completedBookings' : IDL.Nat,
  'pendingVendors' : IDL.Nat,
  'totalVendors' : IDL.Nat,
});
export const NotificationId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Notification = IDL.Record({
  'id' : NotificationId,
  'bookingId' : BookingId,
  'createdAt' : Timestamp,
  'message' : IDL.Text,
  'vendorId' : IDL.Principal,
});
export const VendorBookingStats = IDL.Record({
  'newBookings' : IDL.Nat,
  'cancelledBookings' : IDL.Nat,
  'totalBookings' : IDL.Nat,
  'confirmedBookings' : IDL.Nat,
  'completedBookings' : IDL.Nat,
});
export const VendorStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const VendorInfo = IDL.Record({
  'status' : VendorStatus,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'drivingLicence' : ExternalBlob,
  'companyName' : IDL.Text,
  'aadhaarCard' : ExternalBlob,
  'mobile' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const Facility = IDL.Record({
  'id' : FacilityId,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
});
export const City = IDL.Record({ 'city' : IDL.Text, 'state' : IDL.Text });
export const VendorSignupInput = IDL.Record({
  'name' : IDL.Text,
  'drivingLicence' : ExternalBlob,
  'companyName' : IDL.Text,
  'aadhaarCard' : ExternalBlob,
  'passwordHash' : IDL.Text,
  'mobile' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addCab' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminCreateBooking' : IDL.Func([BookingInput], [BookingId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBooking' : IDL.Func([BookingInput], [BookingId], []),
  'createFacility' : IDL.Func([FacilityInput], [FacilityId], []),
  'deleteFacility' : IDL.Func([FacilityId], [], []),
  'getAllCabs' : IDL.Func([], [IDL.Vec(Cab)], ['query']),
  'getBooking' : IDL.Func([BookingId], [IDL.Opt(Booking)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getLatestNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getMyBookingStats' : IDL.Func([], [VendorBookingStats], ['query']),
  'getMyVendorProfile' : IDL.Func([], [IDL.Opt(VendorInfo)], ['query']),
  'getVendorBookingStats' : IDL.Func(
      [IDL.Principal],
      [VendorBookingStats],
      ['query'],
    ),
  'getVendorCabs' : IDL.Func([], [IDL.Vec(Cab)], ['query']),
  'getVendorNotifications' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getVendorProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(VendorInfo)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllBookings' : IDL.Func(
      [IDL.Opt(IDL.Principal)],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'listAllVendors' : IDL.Func([], [IDL.Vec(VendorInfo)], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listFacilities' : IDL.Func([], [IDL.Vec(Facility)], ['query']),
  'listMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'searchCities' : IDL.Func([IDL.Text], [IDL.Vec(City)], ['query']),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setDriverDetails' : IDL.Func(
      [BookingId, DriverDetails],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'setVendorStatus' : IDL.Func([IDL.Principal, VendorStatus], [], []),
  'updateBookingStatus' : IDL.Func([BookingId, BookingStatus], [], []),
  'updateFacility' : IDL.Func([FacilityId, FacilityInput], [], []),
  'vendorLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Principal)],
      ['query'],
    ),
  'vendorSignup' : IDL.Func(
      [VendorSignupInput],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const BookingType = IDL.Variant({
    'local' : IDL.Null,
    'roundTrip' : IDL.Null,
    'oneWay' : IDL.Null,
  });
  const BookingInput = IDL.Record({
    'submitterName' : IDL.Text,
    'submitterMobile' : IDL.Text,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'commission' : IDL.Nat,
    'submitterWhatsApp' : IDL.Text,
    'pickupCity' : IDL.Text,
    'pickupState' : IDL.Text,
    'driverEarning' : IDL.Nat,
    'bookingType' : BookingType,
    'dropState' : IDL.Text,
    'dropCity' : IDL.Text,
  });
  const BookingId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FacilityInput = IDL.Record({
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const FacilityId = IDL.Nat;
  const CabId = IDL.Nat;
  const Cab = IDL.Record({
    'id' : CabId,
    'carModel' : IDL.Text,
    'driverMobile' : IDL.Text,
    'createdAt' : IDL.Int,
    'vendorId' : IDL.Principal,
    'rcBook' : IDL.Text,
    'driverName' : IDL.Text,
  });
  const BookingStatus = IDL.Variant({
    'new' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DriverDetails = IDL.Record({
    'carModel' : IDL.Text,
    'mobile' : IDL.Text,
    'rcBook' : ExternalBlob,
    'driverName' : IDL.Text,
  });
  const Booking = IDL.Record({
    'id' : BookingId,
    'status' : BookingStatus,
    'submitterName' : IDL.Text,
    'driverDetails' : IDL.Opt(DriverDetails),
    'submitterMobile' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'time' : IDL.Text,
    'vendorPrincipal' : IDL.Principal,
    'commission' : IDL.Nat,
    'submitterWhatsApp' : IDL.Text,
    'pickupCity' : IDL.Text,
    'pickupState' : IDL.Text,
    'driverEarning' : IDL.Nat,
    'bookingType' : BookingType,
    'dropState' : IDL.Text,
    'vendorName' : IDL.Text,
    'dropCity' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'newBookings' : IDL.Nat,
    'cancelledBookings' : IDL.Nat,
    'totalBookings' : IDL.Nat,
    'approvedVendors' : IDL.Nat,
    'confirmedBookings' : IDL.Nat,
    'completedBookings' : IDL.Nat,
    'pendingVendors' : IDL.Nat,
    'totalVendors' : IDL.Nat,
  });
  const NotificationId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Notification = IDL.Record({
    'id' : NotificationId,
    'bookingId' : BookingId,
    'createdAt' : Timestamp,
    'message' : IDL.Text,
    'vendorId' : IDL.Principal,
  });
  const VendorBookingStats = IDL.Record({
    'newBookings' : IDL.Nat,
    'cancelledBookings' : IDL.Nat,
    'totalBookings' : IDL.Nat,
    'confirmedBookings' : IDL.Nat,
    'completedBookings' : IDL.Nat,
  });
  const VendorStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const VendorInfo = IDL.Record({
    'status' : VendorStatus,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'drivingLicence' : ExternalBlob,
    'companyName' : IDL.Text,
    'aadhaarCard' : ExternalBlob,
    'mobile' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const Facility = IDL.Record({
    'id' : FacilityId,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
  });
  const City = IDL.Record({ 'city' : IDL.Text, 'state' : IDL.Text });
  const VendorSignupInput = IDL.Record({
    'name' : IDL.Text,
    'drivingLicence' : ExternalBlob,
    'companyName' : IDL.Text,
    'aadhaarCard' : ExternalBlob,
    'passwordHash' : IDL.Text,
    'mobile' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addCab' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminCreateBooking' : IDL.Func([BookingInput], [BookingId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBooking' : IDL.Func([BookingInput], [BookingId], []),
    'createFacility' : IDL.Func([FacilityInput], [FacilityId], []),
    'deleteFacility' : IDL.Func([FacilityId], [], []),
    'getAllCabs' : IDL.Func([], [IDL.Vec(Cab)], ['query']),
    'getBooking' : IDL.Func([BookingId], [IDL.Opt(Booking)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getLatestNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getMyBookingStats' : IDL.Func([], [VendorBookingStats], ['query']),
    'getMyVendorProfile' : IDL.Func([], [IDL.Opt(VendorInfo)], ['query']),
    'getVendorBookingStats' : IDL.Func(
        [IDL.Principal],
        [VendorBookingStats],
        ['query'],
      ),
    'getVendorCabs' : IDL.Func([], [IDL.Vec(Cab)], ['query']),
    'getVendorNotifications' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getVendorProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(VendorInfo)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllBookings' : IDL.Func(
        [IDL.Opt(IDL.Principal)],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'listAllVendors' : IDL.Func([], [IDL.Vec(VendorInfo)], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listFacilities' : IDL.Func([], [IDL.Vec(Facility)], ['query']),
    'listMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'searchCities' : IDL.Func([IDL.Text], [IDL.Vec(City)], ['query']),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setDriverDetails' : IDL.Func(
        [BookingId, DriverDetails],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'setVendorStatus' : IDL.Func([IDL.Principal, VendorStatus], [], []),
    'updateBookingStatus' : IDL.Func([BookingId, BookingStatus], [], []),
    'updateFacility' : IDL.Func([FacilityId, FacilityInput], [], []),
    'vendorLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'vendorSignup' : IDL.Func(
        [VendorSignupInput],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };