/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Booking {
  'id' : BookingId,
  'status' : BookingStatus,
  'submitterName' : string,
  'driverDetails' : [] | [DriverDetails],
  'submitterMobile' : string,
  'date' : string,
  'createdAt' : bigint,
  'time' : string,
  'vendorPrincipal' : Principal,
  'commission' : bigint,
  'submitterWhatsApp' : string,
  'pickupCity' : string,
  'pickupState' : string,
  'driverEarning' : bigint,
  'bookingType' : BookingType,
  'dropState' : string,
  'dropCity' : string,
}
export type BookingId = bigint;
export interface BookingInput {
  'submitterName' : string,
  'submitterMobile' : string,
  'date' : string,
  'time' : string,
  'commission' : bigint,
  'submitterWhatsApp' : string,
  'pickupCity' : string,
  'pickupState' : string,
  'driverEarning' : bigint,
  'bookingType' : BookingType,
  'dropState' : string,
  'dropCity' : string,
}
export type BookingStatus = { 'new' : null } |
  { 'cancelled' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export type BookingType = { 'local' : null } |
  { 'roundTrip' : null } |
  { 'oneWay' : null };
export interface City { 'city' : string, 'state' : string }
export interface DashboardStats {
  'newBookings' : bigint,
  'cancelledBookings' : bigint,
  'totalBookings' : bigint,
  'approvedVendors' : bigint,
  'confirmedBookings' : bigint,
  'completedBookings' : bigint,
  'pendingVendors' : bigint,
  'totalVendors' : bigint,
}
export interface DriverDetails {
  'carModel' : string,
  'mobile' : string,
  'rcBook' : ExternalBlob,
  'driverName' : string,
}
export type ExternalBlob = Uint8Array;
export interface Facility {
  'id' : FacilityId,
  'active' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
}
export type FacilityId = bigint;
export interface FacilityInput {
  'active' : boolean,
  'name' : string,
  'description' : string,
}
export interface Notification {
  'id' : NotificationId,
  'bookingId' : BookingId,
  'createdAt' : Timestamp,
  'message' : string,
  'vendorId' : Principal,
}
export type NotificationId = bigint;
export type Timestamp = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VendorInfo {
  'status' : VendorStatus,
  'principal' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'drivingLicence' : ExternalBlob,
  'companyName' : string,
  'aadhaarCard' : ExternalBlob,
  'mobile' : string,
}
export interface VendorSignupInput {
  'name' : string,
  'drivingLicence' : ExternalBlob,
  'companyName' : string,
  'aadhaarCard' : ExternalBlob,
  'passwordHash' : string,
  'mobile' : string,
}
export type VendorStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'adminCreateBooking' : ActorMethod<[Principal, BookingInput], BookingId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBooking' : ActorMethod<[BookingInput], BookingId>,
  'createFacility' : ActorMethod<[FacilityInput], FacilityId>,
  'deleteFacility' : ActorMethod<[FacilityId], undefined>,
  'getBooking' : ActorMethod<[BookingId], [] | [Booking]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getLatestNotifications' : ActorMethod<[], Array<Notification>>,
  'getMyVendorProfile' : ActorMethod<[], [] | [VendorInfo]>,
  'getVendorNotifications' : ActorMethod<[Principal], Array<Notification>>,
  'getVendorProfile' : ActorMethod<[Principal], [] | [VendorInfo]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listAllBookings' : ActorMethod<[[] | [Principal]], Array<Booking>>,
  'listAllVendors' : ActorMethod<[], Array<VendorInfo>>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listFacilities' : ActorMethod<[], Array<Facility>>,
  'listMyBookings' : ActorMethod<[], Array<Booking>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'searchCities' : ActorMethod<[string], Array<City>>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setDriverDetails' : ActorMethod<[BookingId, DriverDetails], undefined>,
  'setVendorStatus' : ActorMethod<[Principal, VendorStatus], undefined>,
  'updateBookingStatus' : ActorMethod<[BookingId, BookingStatus], undefined>,
  'updateFacility' : ActorMethod<[FacilityId, FacilityInput], undefined>,
  'vendorLogin' : ActorMethod<[string, string], [] | [Principal]>,
  'vendorSignup' : ActorMethod<[VendorSignupInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];