/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type BookingId = bigint;
export type Timestamp = bigint;
export interface Cab {
    id: CabId;
    carModel: string;
    driverMobile: string;
    createdAt: bigint;
    rcNumber: string;
    vendorId: Principal;
    rcBook: string;
    driverName: string;
}
export interface VendorSignupInput {
    name: string;
    drivingLicence: ExternalBlob;
    companyName: string;
    aadhaarCard: ExternalBlob;
    passwordHash: string;
    mobile: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type FacilityId = bigint;
export interface Facility {
    id: FacilityId;
    active: boolean;
    name: string;
    createdAt: bigint;
    description: string;
}
export interface DriverDetails {
    carModel: string;
    rcNumber: string;
    mobile: string;
    rcBook: ExternalBlob;
    driverName: string;
}
export interface DashboardStats {
    newBookings: bigint;
    cancelledBookings: bigint;
    totalBookings: bigint;
    approvedVendors: bigint;
    confirmedBookings: bigint;
    completedBookings: bigint;
    pendingVendors: bigint;
    totalVendors: bigint;
}
export interface FacilityInput {
    active: boolean;
    name: string;
    description: string;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface City {
    city: string;
    state: string;
}
export type CabId = bigint;
export type NotificationId = bigint;
export interface Notification {
    id: NotificationId;
    bookingId: BookingId;
    createdAt: Timestamp;
    message: string;
    vendorId: Principal;
}
export interface VendorBookingStats {
    newBookings: bigint;
    cancelledBookings: bigint;
    totalBookings: bigint;
    confirmedBookings: bigint;
    completedBookings: bigint;
}
export interface Booking {
    id: BookingId;
    status: BookingStatus;
    submitterName: string;
    driverDetails?: DriverDetails;
    submitterMobile: string;
    date: string;
    createdAt: bigint;
    time: string;
    vendorPrincipal: Principal;
    commission: bigint;
    submitterWhatsApp: string;
    pickupCity: string;
    pickupState: string;
    driverEarning: bigint;
    bookingType: BookingType;
    dropState: string;
    vendorName: string;
    dropCity: string;
}
export interface BookingInput {
    submitterName: string;
    submitterMobile: string;
    date: string;
    time: string;
    commission: bigint;
    submitterWhatsApp: string;
    pickupCity: string;
    pickupState: string;
    driverEarning: bigint;
    bookingType: BookingType;
    dropState: string;
    dropCity: string;
}
export interface VendorInfo {
    status: VendorStatus;
    principal: Principal;
    name: string;
    createdAt: bigint;
    drivingLicence: ExternalBlob;
    companyName: string;
    aadhaarCard: ExternalBlob;
    mobile: string;
}
export enum BookingStatus {
    new_ = "new",
    cancelled = "cancelled",
    completed = "completed",
    confirmed = "confirmed"
}
export enum BookingType {
    local = "local",
    roundTrip = "roundTrip",
    oneWay = "oneWay"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VendorStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addCab(driverName: string, driverMobile: string, carModel: string, rcBook: string, rcNumber: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminCreateBooking(input: BookingInput): Promise<BookingId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBooking(input: BookingInput): Promise<BookingId>;
    createFacility(input: FacilityInput): Promise<FacilityId>;
    deleteFacility(id: FacilityId): Promise<void>;
    getAllCabs(): Promise<Array<Cab>>;
    getBooking(id: BookingId): Promise<Booking | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getLatestNotifications(): Promise<Array<Notification>>;
    getMyBookingStats(): Promise<VendorBookingStats>;
    getMyVendorProfile(): Promise<VendorInfo | null>;
    getVendorBookingStats(vendorPrincipal: Principal): Promise<VendorBookingStats>;
    getVendorCabs(): Promise<Array<Cab>>;
    getVendorNotifications(vendorId: Principal): Promise<Array<Notification>>;
    getVendorProfile(principal: Principal): Promise<VendorInfo | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listAllBookings(vendorFilter: Principal | null): Promise<Array<Booking>>;
    listAllVendors(): Promise<Array<VendorInfo>>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    listFacilities(): Promise<Array<Facility>>;
    listMyBookings(): Promise<Array<Booking>>;
    requestApproval(): Promise<void>;
    searchCities(prefix: string): Promise<Array<City>>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setDriverDetails(id: BookingId, details: DriverDetails): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setVendorStatus(principal: Principal, status: VendorStatus): Promise<void>;
    updateBookingStatus(id: BookingId, status: BookingStatus): Promise<void>;
    updateFacility(id: FacilityId, input: FacilityInput): Promise<void>;
    vendorLogin(mobile: string, passwordHash: string): Promise<Principal | null>;
    vendorSignup(input: VendorSignupInput): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { ApprovalStatus as _ApprovalStatus, Booking as _Booking, BookingId as _BookingId, BookingInput as _BookingInput, BookingStatus as _BookingStatus, BookingType as _BookingType, DriverDetails as _DriverDetails, ExternalBlob as _ExternalBlob, UserApprovalInfo as _UserApprovalInfo, UserRole as _UserRole, VendorInfo as _VendorInfo, VendorSignupInput as _VendorSignupInput, VendorStatus as _VendorStatus, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addCab(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addCab(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCab(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminCreateBooking(arg0: BookingInput): Promise<BookingId> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateBooking(to_candid_BookingInput_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateBooking(to_candid_BookingInput_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBooking(arg0: BookingInput): Promise<BookingId> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(to_candid_BookingInput_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(to_candid_BookingInput_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createFacility(arg0: FacilityInput): Promise<FacilityId> {
        if (this.processError) {
            try {
                const result = await this.actor.createFacility(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFacility(arg0);
            return result;
        }
    }
    async deleteFacility(arg0: FacilityId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFacility(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFacility(arg0);
            return result;
        }
    }
    async getAllCabs(): Promise<Array<Cab>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCabs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCabs();
            return result;
        }
    }
    async getBooking(arg0: BookingId): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getLatestNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestNotifications();
            return result;
        }
    }
    async getMyBookingStats(): Promise<VendorBookingStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBookingStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBookingStats();
            return result;
        }
    }
    async getMyVendorProfile(): Promise<VendorInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyVendorProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyVendorProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVendorBookingStats(arg0: Principal): Promise<VendorBookingStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendorBookingStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendorBookingStats(arg0);
            return result;
        }
    }
    async getVendorCabs(): Promise<Array<Cab>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendorCabs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendorCabs();
            return result;
        }
    }
    async getVendorNotifications(arg0: Principal): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendorNotifications(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendorNotifications(arg0);
            return result;
        }
    }
    async getVendorProfile(arg0: Principal): Promise<VendorInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendorProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendorProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listAllBookings(arg0: Principal | null): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllBookings(to_candid_opt_n33(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllBookings(to_candid_opt_n33(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllVendors(): Promise<Array<VendorInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllVendors();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllVendors();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFacilities(): Promise<Array<Facility>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFacilities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFacilities();
            return result;
        }
    }
    async listMyBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyBookings();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyBookings();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async searchCities(arg0: string): Promise<Array<City>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchCities(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchCities(arg0);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n40(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n40(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setDriverDetails(arg0: BookingId, arg1: DriverDetails): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setDriverDetails(arg0, await to_candid_DriverDetails_n42(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDriverDetails(arg0, await to_candid_DriverDetails_n42(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async setVendorStatus(arg0: Principal, arg1: VendorStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setVendorStatus(arg0, to_candid_VendorStatus_n45(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setVendorStatus(arg0, to_candid_VendorStatus_n45(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateBookingStatus(arg0: BookingId, arg1: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n46(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n46(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateFacility(arg0: FacilityId, arg1: FacilityInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFacility(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFacility(arg0, arg1);
            return result;
        }
    }
    async vendorLogin(arg0: string, arg1: string): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.vendorLogin(arg0, arg1);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.vendorLogin(arg0, arg1);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async vendorSignup(arg0: VendorSignupInput): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.vendorSignup(await to_candid_VendorSignupInput_n49(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.vendorSignup(await to_candid_VendorSignupInput_n49(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ApprovalStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_BookingType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingType): BookingType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_Booking_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Promise<Booking> {
    return await from_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_DriverDetails_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DriverDetails): Promise<DriverDetails> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_UserApprovalInfo_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_VendorInfo_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VendorInfo): Promise<VendorInfo> {
    return await from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_VendorStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VendorStatus): VendorStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Promise<Booking | null> {
    return value.length === 0 ? null : await from_candid_Booking_n16(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DriverDetails]): Promise<DriverDetails | null> {
    return value.length === 0 ? null : await from_candid_DriverDetails_n21(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VendorInfo]): Promise<VendorInfo | null> {
    return value.length === 0 ? null : await from_candid_VendorInfo_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BookingId;
    status: _BookingStatus;
    submitterName: string;
    driverDetails: [] | [_DriverDetails];
    submitterMobile: string;
    date: string;
    createdAt: bigint;
    time: string;
    vendorPrincipal: Principal;
    commission: bigint;
    submitterWhatsApp: string;
    pickupCity: string;
    pickupState: string;
    driverEarning: bigint;
    bookingType: _BookingType;
    dropState: string;
    vendorName: string;
    dropCity: string;
}): Promise<{
    id: BookingId;
    status: BookingStatus;
    submitterName: string;
    driverDetails?: DriverDetails;
    submitterMobile: string;
    date: string;
    createdAt: bigint;
    time: string;
    vendorPrincipal: Principal;
    commission: bigint;
    submitterWhatsApp: string;
    pickupCity: string;
    pickupState: string;
    driverEarning: bigint;
    bookingType: BookingType;
    dropState: string;
    vendorName: string;
    dropCity: string;
}> {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n18(_uploadFile, _downloadFile, value.status),
        submitterName: value.submitterName,
        driverDetails: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.driverDetails)),
        submitterMobile: value.submitterMobile,
        date: value.date,
        createdAt: value.createdAt,
        time: value.time,
        vendorPrincipal: value.vendorPrincipal,
        commission: value.commission,
        submitterWhatsApp: value.submitterWhatsApp,
        pickupCity: value.pickupCity,
        pickupState: value.pickupState,
        driverEarning: value.driverEarning,
        bookingType: from_candid_BookingType_n24(_uploadFile, _downloadFile, value.bookingType),
        dropState: value.dropState,
        vendorName: value.vendorName,
        dropCity: value.dropCity
    };
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    carModel: string;
    rcNumber: string;
    mobile: string;
    rcBook: _ExternalBlob;
    driverName: string;
}): Promise<{
    carModel: string;
    rcNumber: string;
    mobile: string;
    rcBook: ExternalBlob;
    driverName: string;
}> {
    return {
        carModel: value.carModel,
        rcNumber: value.rcNumber,
        mobile: value.mobile,
        rcBook: await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value.rcBook),
        driverName: value.driverName
    };
}
async function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _VendorStatus;
    principal: Principal;
    name: string;
    createdAt: bigint;
    drivingLicence: _ExternalBlob;
    companyName: string;
    aadhaarCard: _ExternalBlob;
    mobile: string;
}): Promise<{
    status: VendorStatus;
    principal: Principal;
    name: string;
    createdAt: bigint;
    drivingLicence: ExternalBlob;
    companyName: string;
    aadhaarCard: ExternalBlob;
    mobile: string;
}> {
    return {
        status: from_candid_VendorStatus_n31(_uploadFile, _downloadFile, value.status),
        principal: value.principal,
        name: value.name,
        createdAt: value.createdAt,
        drivingLicence: await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value.drivingLicence),
        companyName: value.companyName,
        aadhaarCard: await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value.aadhaarCard),
        mobile: value.mobile
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n39(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    cancelled: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "new" in value ? BookingStatus.new : "cancelled" in value ? BookingStatus.cancelled : "completed" in value ? BookingStatus.completed : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    local: null;
} | {
    roundTrip: null;
} | {
    oneWay: null;
}): BookingType {
    return "local" in value ? BookingType.local : "roundTrip" in value ? BookingType.roundTrip : "oneWay" in value ? BookingType.oneWay : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): VendorStatus {
    return "pending" in value ? VendorStatus.pending : "approved" in value ? VendorStatus.approved : "rejected" in value ? VendorStatus.rejected : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Promise<Array<Booking>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Booking_n16(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VendorInfo>): Promise<Array<VendorInfo>> {
    return await Promise.all(value.map(async (x)=>await from_candid_VendorInfo_n29(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n37(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_BookingInput_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingInput): _BookingInput {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_BookingStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_BookingType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingType): _BookingType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
async function to_candid_DriverDetails_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DriverDetails): Promise<_DriverDetails> {
    return await to_candid_record_n43(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
async function to_candid_VendorSignupInput_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VendorSignupInput): Promise<_VendorSignupInput> {
    return await to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_VendorStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VendorStatus): _VendorStatus {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submitterName: string;
    submitterMobile: string;
    date: string;
    time: string;
    commission: bigint;
    submitterWhatsApp: string;
    pickupCity: string;
    pickupState: string;
    driverEarning: bigint;
    bookingType: BookingType;
    dropState: string;
    dropCity: string;
}): {
    submitterName: string;
    submitterMobile: string;
    date: string;
    time: string;
    commission: bigint;
    submitterWhatsApp: string;
    pickupCity: string;
    pickupState: string;
    driverEarning: bigint;
    bookingType: _BookingType;
    dropState: string;
    dropCity: string;
} {
    return {
        submitterName: value.submitterName,
        submitterMobile: value.submitterMobile,
        date: value.date,
        time: value.time,
        commission: value.commission,
        submitterWhatsApp: value.submitterWhatsApp,
        pickupCity: value.pickupCity,
        pickupState: value.pickupState,
        driverEarning: value.driverEarning,
        bookingType: to_candid_BookingType_n11(_uploadFile, _downloadFile, value.bookingType),
        dropState: value.dropState,
        dropCity: value.dropCity
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    carModel: string;
    rcNumber: string;
    mobile: string;
    rcBook: ExternalBlob;
    driverName: string;
}): Promise<{
    carModel: string;
    rcNumber: string;
    mobile: string;
    rcBook: _ExternalBlob;
    driverName: string;
}> {
    return {
        carModel: value.carModel,
        rcNumber: value.rcNumber,
        mobile: value.mobile,
        rcBook: await to_candid_ExternalBlob_n44(_uploadFile, _downloadFile, value.rcBook),
        driverName: value.driverName
    };
}
async function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    drivingLicence: ExternalBlob;
    companyName: string;
    aadhaarCard: ExternalBlob;
    passwordHash: string;
    mobile: string;
}): Promise<{
    name: string;
    drivingLicence: _ExternalBlob;
    companyName: string;
    aadhaarCard: _ExternalBlob;
    passwordHash: string;
    mobile: string;
}> {
    return {
        name: value.name,
        drivingLicence: await to_candid_ExternalBlob_n44(_uploadFile, _downloadFile, value.drivingLicence),
        companyName: value.companyName,
        aadhaarCard: await to_candid_ExternalBlob_n44(_uploadFile, _downloadFile, value.aadhaarCard),
        passwordHash: value.passwordHash,
        mobile: value.mobile
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingType): {
    local: null;
} | {
    roundTrip: null;
} | {
    oneWay: null;
} {
    return value == BookingType.local ? {
        local: null
    } : value == BookingType.roundTrip ? {
        roundTrip: null
    } : value == BookingType.oneWay ? {
        oneWay: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VendorStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == VendorStatus.pending ? {
        pending: null
    } : value == VendorStatus.approved ? {
        approved: null
    } : value == VendorStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    new: null;
} | {
    cancelled: null;
} | {
    completed: null;
} | {
    confirmed: null;
} {
    return value == BookingStatus.new ? {
        new_: null
    } : value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.completed ? {
        completed: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
